stages:
  - deploy

pages:
  image: node:latest
  stage: deploy
  script:
    - npm install gatsby -g
    - npm install -f
    - ./node_modules/.bin/gatsby build --prefix-paths
  artifacts:
    paths:
      - public
  only:
    - main
